use crate::ast::*;

pub struct Codegen {
    result: String,
    indent: usize,
    // Track which boxes we've generated module headers for
    generated_modules: Vec<String>,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            result: String::new(),
            indent: 0,
            generated_modules: Vec::new(),
        }
    }

    pub fn generate(&mut self, program: &HakoProgram) -> String {
        self.result.clear();
        self.generated_modules.clear();

        // Generate module declarations from boxes
        for b in &program.boxes {
            self.emit_module(b);
        }

        self.result.clone()
    }

    fn emit_module(&mut self, b: &HakoBox) {
        self.emit_line(&format!("pub mod {} {{", b.name));
        self.indent += 1;

        // Find implementations for this box
        // Generate function signatures from declarations + implementations

        // First, collect all instructions and their implementations
        for inst in &b.instructions {
            self.emit_inst_sig(b, inst);
        }

        self.indent -= 1;
        self.emit_line("}");
        self.generated_modules.push(b.name.clone());
    }

    /// Emit a function signature and body for a box instruction.
    /// Looks up the corresponding implementation, or generates a stub.
    fn emit_inst_sig(&mut self, b: &HakoBox, inst: &HakoInstDecl) {
        // We'll look for a matching impl among the program's impls.
        // The Codegen doesn't have direct access to all impls, so we need
        // to pass them in. For now, inline all impl content.
        
        // Build the function signature
        let mut sig = String::from("pub fn ");
        sig.push_str(&inst.name);
        sig.push('(');
        for (i, p) in inst.params.iter().enumerate() {
            if i > 0 { sig.push_str(", "); }
            sig.push_str(&p.name);
            sig.push_str(": ");
            sig.push_str(&p.type_name);
        }
        sig.push(')');
        if let Some(ref rt) = inst.ret_type {
            sig.push_str(" -> ");
            sig.push_str(rt);
        }
        sig.push_str(" {\n");
        self.emit(&sig);
        self.indent += 1;

        // We'll emit the body later when we process impls
        // For now, just a placeholder
        self.emit_line("loop {}");
        self.indent -= 1;
        self.emit_line("}");
    }

    /// Generate the real implementation bodies (after module declarations)
    pub fn generate_impls(&mut self, program: &HakoProgram) -> String {
        // We need to inject impl bodies into the module structure.
        // For simplicity, we generate standalone functions in separate files
        // that are called from the module wrappers.
        // 
        // Actually, let's take a different approach: generate everything in one pass.
        String::new()
    }

    /// Generate Rust code for a single implementation
    pub fn generate_impl(&mut self, imp: &HakoImpl) -> String {
        let mut code = String::new();
        code.push_str(&format!("fn {}__{}(", imp.box_name, imp.inst_name));
        for (i, p) in imp.params.iter().enumerate() {
            if i > 0 { code.push_str(", "); }
            code.push_str(&p.name);
            code.push_str(": ");
            code.push_str(&p.type_name);
        }
        code.push(')');
        if let Some(ref rt) = imp.ret_type {
            code.push_str(" -> ");
            code.push_str(rt);
        }
        code.push_str(" {\n");
        for stmt in &imp.body {
            code.push_str(&self.stmt_to_string(stmt, 1));
        }
        code.push_str("}\n");
        code
    }

    // ===== Two-pass generation =====

    pub fn generate_full(&mut self, program: &HakoProgram) -> String {
        self.result.clear();
        self.result.push_str("// Generated by Hako transpiler\n");
        self.result.push_str("// do not edit\n\n");

        // First, generate module structures with function stubs
        for b in &program.boxes {
            self.result.push_str(&format!("pub mod {} {{\n    use super::*;\n\n", b.name));
            for inst in &b.instructions {
                // Find matching impl
                let matching_impl = program.impls.iter().find(|imp| {
                    imp.box_name == b.name && imp.inst_name == inst.name && 
                    imp.params.len() == inst.params.len()
                });

                self.result.push_str("    ");
                self.result.push_str(&format!("pub fn {}(", inst.name));
                for (i, p) in inst.params.iter().enumerate() {
                    if i > 0 { self.result.push_str(", "); }
                    self.result.push_str(&p.name);
                    self.result.push_str(": ");
                    self.result.push_str(&p.type_name);
                }
                self.result.push(')');
                if let Some(ref rt) = inst.ret_type {
                    self.result.push_str(" -> ");
                    self.result.push_str(rt);
                }
                self.result.push_str(" {\n");

                if let Some(imp) = matching_impl {
                    for stmt in &imp.body {
                        self.result.push_str(&self.stmt_to_string(stmt, 2));
                    }
                } else {
                    // Stub - call unimplemented!() or loop {}
                    self.result.push_str("        loop {}\n");
                }
                self.result.push_str("    }\n\n");
            }
            self.result.push_str("}\n\n");
        }

        // Generate any standalone impls that don't have box declarations
        // (already handled above)

        self.result.clone()
    }

    fn stmt_to_string(&self, stmt: &HakoStmt, indent: usize) -> String {
        let ind = "    ".repeat(indent);
        match stmt {
            HakoStmt::Let { name, type_name, is_mut, value } => {
                let mut s = format!("{}let {}{}", ind, if *is_mut { "mut " } else { "" }, name);
                if let Some(ref t) = type_name { s.push_str(&format!(": {}", t)); }
                if let Some(ref v) = value { s.push_str(&format!(" = {}", v)); }
                s.push_str(";\n");
                s
            }
            HakoStmt::Expr(e) => {
                format!("{}{};\n", ind, e)
            }
            HakoStmt::Caso { cond, body } => {
                let mut s = format!("{}if {} {{\n", ind, cond);
                for stmt in body {
                    s.push_str(&self.stmt_to_string(stmt, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            HakoStmt::CasoContrario(body) => {
                let mut s = format!("{}else {{\n", ind);
                for stmt in body {
                    s.push_str(&self.stmt_to_string(stmt, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            HakoStmt::Retorna(v) => {
                if let Some(ref v) = v {
                    format!("{}return {};\n", ind, v)
                } else {
                    format!("{}return;\n", ind)
                }
            }
            HakoStmt::Asm { template, operands, clobbers } => {
                let mut s = format!("{}unsafe {{ core::arch::asm!(\"{}\"", ind, template);
                for op in operands {
                    s.push_str(", ");
                    s.push_str(op);
                }
                for cl in clobbers {
                    s.push_str(", ");
                    s.push_str(cl);
                }
                s.push_str("); }");
                s.push('\n');
                s
            }
            HakoStmt::Loop(body) => {
                let mut s = format!("{}loop {{\n", ind);
                for stmt in body {
                    s.push_str(&self.stmt_to_string(stmt, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            HakoStmt::For { var, iter, body } => {
                let mut s = format!("{}for {} in {} {{\n", ind, var, iter);
                for stmt in body {
                    s.push_str(&self.stmt_to_string(stmt, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            HakoStmt::Block(body) => {
                let mut s = format!("{} {{\n", ind);
                for stmt in body {
                    s.push_str(&self.stmt_to_string(stmt, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            HakoStmt::Ref(r) => {
                format!("{}{};\n", ind, r)
            }
            HakoStmt::Empty => String::new(),
        }
    }

    fn emit_line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.result.push_str(&indent);
        self.result.push_str(s);
        self.result.push('\n');
    }

    fn emit(&mut self, s: &str) {
        self.result.push_str(s);
    }
}
