use crate::ast::*;

pub struct Codegen {
    result: String,
    // Track box constants for auto-mode argument injection
    box_consts: Vec<(String, String)>, // (name, value)
}

impl Codegen {
    pub fn new() -> Self { Self { result: String::new(), box_consts: Vec::new() } }

    pub fn generate_full(&mut self, program: &Program) -> String {
        self.result.clear();
        self.result.push_str("// Generated by Hako transpiler\n\n");

        // Include stdlib module
        self.result.push_str("pub mod hako_stdlib {\n");
        self.result.push_str(&crate::stdlib::STDLIB);
        self.result.push_str("}\n\n");

        for b in &program.boxes {
            let mod_name = if let Some(ref ext) = b.extends {
                format!("{}_{}", b.name, ext)
            } else {
                b.name.clone()
            };
            self.result.push_str(&format!("pub mod {} {{\n    use super::*;\n\n", mod_name));
            self.box_consts.clear();

            for item in &b.items {
                match item {
                    Item::Var { name, value } => {
                        let val_str = if let Some(ref v) = value {
                            v.clone()
                        } else {
                            "0".to_string()
                        };
                        self.result.push_str(&format!("    pub const {}: u32 = {};\n", name, val_str));
                        self.box_consts.push((name.clone(), val_str));
                    }
                    Item::Fn { name, params, mode, body } => {
                        self.emit_fn(name, params, mode, body);
                    }
                    Item::Expr(e) => {
                        self.result.push_str(&format!("    // side-effect: {}\n", e));
                    }
                }
            }
            self.result.push_str("}\n\n");
        }

        // Generate flows
        for fl in &program.flows {
            self.result.push_str(&format!("pub fn flow_{}() {{\n", fl.name));
            for step in &fl.steps {
                self.result.push_str(&format!("    {}::run();\n", step));
            }
            self.result.push_str("}\n\n");
        }

        self.result.clone()
    }

    fn emit_fn(&mut self, name: &str, params: &[(String, String)], mode: &FnMode, body: &[Stmt]) {
        self.result.push_str(&format!("    pub fn {}(", name));
        for (i, (p, pt)) in params.iter().enumerate() {
            if i > 0 { self.result.push_str(", "); }
            self.result.push_str(p);
            self.result.push_str(": ");
            self.result.push_str(pt);
        }
        self.result.push_str(") {\n");

        match mode {
            FnMode::Auto => {
                let (stdlib_fn, extra_args) = self.auto_fn_info(name);
                self.result.push_str(&format!("        hako_stdlib::{}(", stdlib_fn));
                // User params first (just the name, not the type)
                for (i, (p, _)) in params.iter().enumerate() {
                    if i > 0 { self.result.push_str(", "); }
                    self.result.push_str(p);
                }
                // Then extra args from box constants
                for a in &extra_args {
                    if !params.is_empty() { self.result.push_str(", "); }
                    self.result.push_str(a);
                }
                // No args at all — close cleanly
                self.result.push_str(");\n");
            }
            FnMode::Block => {
                for s in body {
                    self.result.push_str(&self.stmt_str(s, 2));
                }
            }
            FnMode::Raw => {
                self.emit_raw_block(body);
            }
        }

        self.result.push_str("    }\n\n");
    }

    fn reg_type(reg: &str) -> &'static str {
        match reg {
            "al" | "ah" | "bl" | "bh" | "cl" | "ch" | "dl" | "dh" => "u8",
            "ax" | "bx" | "cx" | "dx" | "si" | "di" | "sp" | "bp" => "u16",
            _ => "u32",
        }
    }

    fn emit_raw_block(&mut self, body: &[Stmt]) {
        // Collect asm operands and template lines
        let mut outputs: Vec<(String, String)> = Vec::new(); // (reg, var)
        let mut inputs: Vec<(String, String)> = Vec::new();  // (reg, var)
        let mut asm_lines: Vec<String> = Vec::new();

        for stmt in body {
            match stmt {
                Stmt::AsmOut { reg, var } => outputs.push((reg.clone(), var.clone())),
                Stmt::AsmIn { reg, var } => inputs.push((reg.clone(), var.clone())),
                Stmt::AsmLine(s) => asm_lines.push(s.clone()),
                Stmt::Expr(s) => asm_lines.push(s.clone()),
                _ => {}
            }
        }

        if asm_lines.is_empty() && outputs.is_empty() && inputs.is_empty() {
            return;
        }

        // Generate let mut for outputs
        for (reg, var) in &outputs {
            let ty = Self::reg_type(reg);
            self.result.push_str(&format!("        let mut __out_{}: {};\n", var, ty));
        }

        // Build asm!() call
        self.result.push_str("        unsafe {\n            core::arch::asm!(\n");

        let mut needs_comma = false;

        // Template strings
        for line in &asm_lines {
            if needs_comma { self.result.push_str(",\n"); }
            self.result.push_str(&format!("                \"{}\"", line));
            needs_comma = true;
        }

        // Input operands
        for (reg, var) in &inputs {
            if needs_comma { self.result.push_str(",\n"); }
            let ty = Self::reg_type(reg);
            if ty == "u32" {
                self.result.push_str(&format!("                in(\"{}\") {}", reg, var));
            } else {
                self.result.push_str(&format!("                in(\"{}\") {} as {}", reg, var, ty));
            }
            needs_comma = true;
        }

        // Output operands
        for (reg, var) in &outputs {
            if needs_comma { self.result.push_str(",\n"); }
            self.result.push_str(&format!("                out(\"{}\") __out_{}", reg, var));
            needs_comma = true;
        }

        self.result.push_str("\n            );\n        }\n");

        // Assign outputs back to original variable names
        for (_, var) in &outputs {
            self.result.push_str(&format!("        let {} = __out_{};\n", var, var));
        }
    }

    /// Returns (stdlib_function_name, extra_arguments_to_pass)
    fn auto_fn_info(&self, name: &str) -> (String, Vec<String>) {
        match name {
            "config" | "setup" => ("serial_config".into(), vec!["COM1".into()]),
            "write_byte" => ("serial_write_byte".into(), vec!["COM1".into()]),
            "read_byte" => ("serial_read_byte".into(), vec!["COM1".into()]),
            "put_char" => ("vga_put_char".into(), vec![]),
            "write" | "write_str" => ("vga_write_str".into(), vec![]),
            "clear" => ("vga_clear".into(), vec![]),
            "scroll" => ("vga_scroll".into(), vec![]),
            "set_cursor" => ("vga_set_cursor".into(), vec![]),
            "outb" => ("port_outb".into(), vec![]),
            "inb" => ("port_inb".into(), vec![]),
            "init" => ("keyboard_init".into(), vec![]),
            _ => (format!("auto_{}", name), vec![]),
        }
    }

    fn stmt_str(&self, stmt: &Stmt, indent: usize) -> String {
        let ind = "    ".repeat(indent);
        match stmt {
            Stmt::If { cond, then, r#else } => {
                let mut s = format!("{}if {} {{\n", ind, cond);
                for st in then { s.push_str(&self.stmt_str(st, indent + 1)); }
                if r#else.is_empty() {
                    s.push_str(&format!("{}}}\n", ind));
                } else {
                    s.push_str(&format!("{}}} else {{\n", ind));
                    for st in r#else { s.push_str(&self.stmt_str(st, indent + 1)); }
                    s.push_str(&format!("{}}}\n", ind));
                }
                s
            }
            Stmt::Loop(body) => {
                let mut s = format!("{}loop {{\n", ind);
                for st in body { s.push_str(&self.stmt_str(st, indent + 1)); }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Stmt::For { var, iter, body } => {
                let mut s = format!("{}for {} in {} {{\n", ind, var, iter);
                for st in body { s.push_str(&self.stmt_str(st, indent + 1)); }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Stmt::Break => format!("{}break;\n", ind),
            Stmt::Assign { var, value } => format!("{}{} = {};\n", ind, var, value),
            Stmt::Expr(e) => format!("{}{};\n", ind, e),
            Stmt::Block(body) => {
                let mut s = format!("{} {{\n", ind);
                for st in body { s.push_str(&self.stmt_str(st, indent + 1)); }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Stmt::AsmOut { .. } | Stmt::AsmIn { .. } | Stmt::AsmLine(_) => String::new(),
        }
    }
}
